import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-league-light text-league-black`}
			>
				<nav className='bg-league-dark border-b border-league-medium shadow-sm'>
					<div className='container mx-auto px-4 py-3 flex justify-between items-center'>
						<div className='text-xl font-bold tracking-tight text-league-light'>
							<Link href='/'>⚽ Soccer League</Link>
						</div>
						<div className='flex items-center space-x-6'>
							<Link
								href='/'
								className='text-league-light hover:text-league-medium'
							>
								Home
							</Link>
							<Link
								href='/leagues'
								className='text-league-light hover:text-league-medium'
							>
								Leagues
							</Link>
							<Link
								href='/login'
								className='ml-4 px-4 py-1 bg-white text-black rounded shadow hover:bg-league-light border border-league-mediumdark font-semibold transition'
							>
								Login
							</Link>
						</div>
					</div>
				</nav>
				<main className='container mx-auto px-4 py-8'>{children}</main>
			</body>
		</html>
	);
}
